pyroscope:
  storage:
    type: s3
    s3:
      bucket: "pyroscope"
      endpoint: "master.sale.elewise.com:9000"
      insecure: false  # Включаем TLS
      existingSecret: "pyroscope-s3-creds"  # Secret с access_key/secret_key
      tls:
        enabled: true
  
  podAnnotations:
    # Scrapes itself see https://grafana.com/docs/pyroscope/latest/deploy-kubernetes/helm/#optional-scrape-your-own-workloads-profiles
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port_name: http2
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port_name: http2