global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  resourcesJobs: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
images:
  service: ci-f6fe32b4
image:
  repository: {}
  pullSecret: {}
nameOverride: checkdbs
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resourcesJobs: {}
resources: {}
connectionschecker:
  labels:
    tier: elma365
    action: checkdbs
annotations:
  ci.elma365.com/commit: "45bca5a3"
  ci.elma365.com/checksum: "f6fe32b4"
  ci.elma365.com/job_id: "3365144"
  ci.elma365.com/timestamp: "2025-06-10T05:34:34+00:00"
  ci.elma365.com/pipeline_id: "594776"
