global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
    lowcode:
      metricExportEnabled: false
      internalOtlpHttpPort: 3001
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-1f218861
image:
  repository: {}
  pullSecret: {}
nameOverride: otelier
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
autoscaling: {}
resourcesJobs: {}
resources:
  requests:
    memory: "256Mi"
    cpu: "150m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
otelier:
  labels:
    app: otelier
ingress:
  annotations: {}
  gzip:
    enabled: true
    compLevel: 5
    minLength: 1024
appconfig:
  httpOtlpPortPublic: 3002
  lowcode:
    metricExportPort: 3300
annotations:
  ci.elma365.com/commit: "c56114a0"
  ci.elma365.com/checksum: "1f218861"
  ci.elma365.com/job_id: "3365473"
  ci.elma365.com/timestamp: "2025-06-09T16:50:02+04:00"
  ci.elma365.com/pipeline_id: "594804"
