apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    # Принудительное обновление секретов
    argocd.argoproj.io/compare-options: IgnoreExtraneous

spec:
  project: default
  source:
    repoURL: https://github.com/LovemeTrue/k8s-multi-node-argocd.git
    targetRevision: main
    path: 0/monitoring
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true

    retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
        
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /metadata/annotations
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      jsonPointers:
        - /metadata/annotations
    - group: batch
      kind: Job
      name: grafana-kube-prometheus-st-admission-create
      jqPathExpressions:
        - '.status'