apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-grafana-monitoring
  namespace: argocd
  labels:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: argocd-admin
      restartPolicy: Never
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "=== 🧹 Cleaning up Grafana / Prometheus stack ==="

              echo "--- Deleting RBAC ---"
              kubectl delete clusterrole grafana-kube-prometheus-st-admission --ignore-not-found
              kubectl delete clusterrolebinding grafana-kube-prometheus-st-admission --ignore-not-found
              kubectl delete role -A grafana-kube-prometheus-st-admission --ignore-not-found
              kubectl delete rolebinding -A grafana-kube-prometheus-st-admission --ignore-not-found

              echo "--- Deleting CRDs ---"
              for crd in \
                alertmanagers.monitoring.coreos.com \
                prometheuses.monitoring.coreos.com \
                prometheusagents.monitoring.coreos.com \
                thanosrulers.monitoring.coreos.com \
                scrapeconfigs.monitoring.coreos.com \
                alertmanagerconfigs.monitoring.coreos.com \
                podmonitors.monitoring.coreos.com \
                servicemonitors.monitoring.coreos.com \
                probes.monitoring.coreos.com; do
                  kubectl delete crd $crd --ignore-not-found
              done

              echo "--- Deleting StatefulSets ---"
              kubectl delete statefulset -n monitoring -l release=grafana-kube-prometheus-st --ignore-not-found

              echo "--- Deleting DaemonSets ---"
              kubectl delete daemonset -n monitoring -l release=grafana-kube-prometheus-st --ignore-not-found

              echo "--- Deleting leftover Deployments ---"
              kubectl delete deployment -n monitoring -l release=grafana-kube-prometheus-st --ignore-not-found

              echo "--- Removing finalizers from Application ---"
              kubectl patch applications.argoproj.io/grafana -n argocd --type=merge -p '{"metadata":{"finalizers":[]}}' || true

              echo "✅ Cleanup complete."