apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/LovemeTrue/k8s-multi-node-argocd.git
    targetRevision: main
    path: 0/pyroscope
    helm:
      valueFiles:
        - pyroscope-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pyroscope
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
