apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LovemeTrue/k8s-multi-node-argocd.git
    targetRevision: main
    path: 0/monitoring/charts/kube-prometheus-stack/charts/crds/crds
    directory:
    recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
